In [1]:
import numpy as np


class Linear:
    def __init__(self, in_features: int, out_feature: int) -> None:
        self.weight = np.random.randn(out_feature, in_features)
        self.bias = np.random.randn(out_feature)

    def __call__(self, x: np.ndarray) -> np.ndarray:
        return self.weight @ x + self.bias

In [2]:
x = np.array([0.1, 0.2, 0.3])

linear = Linear(3, 4)
linear.weight = np.linspace(0.01, 0.12, 12).reshape(3, 4).T
linear.bias = np.linspace(0.13, 0.16, 4)

linear(x)

array([0.168, 0.184, 0.2  , 0.216])

In [3]:
linear.weight

array([[0.01, 0.05, 0.09],
       [0.02, 0.06, 0.1 ],
       [0.03, 0.07, 0.11],
       [0.04, 0.08, 0.12]])

In [4]:
linear.bias

array([0.13, 0.14, 0.15, 0.16])

---

In [5]:
import torch
from torch import nn

linear = nn.Linear(3, 4)

In [6]:
x = torch.tensor([0.1, 0.2, 0.3]).unsqueeze(0)

weight = torch.linspace(0.01, 0.12, 12).reshape(3, 4).T
bias = torch.linspace(0.13, 0.16, 4)
linear.weight = nn.Parameter(weight)
linear.bias = nn.Parameter(bias)

linear(x)

tensor([[0.1680, 0.1840, 0.2000, 0.2160]], grad_fn=<AddmmBackward0>)